global using FluentAssertions;
global using MatchCardGame.Constants;
global using MatchCardGame.Interfaces;
global using MatchCardGame.Services;
global using MatchCardGame.Models;
global using MatchCardGame.Wrapper;
global using Moq;
global using Microsoft.Extensions.DependencyInjection;
global using System.Diagnostics.CodeAnalysis;
